/**
 * Dados de seed a partir do mockData original.
 * Datas calculadas em tempo de carga para manter coerência.
 */
const NOW = Date.now();
const TODAY = new Date(NOW);
const YESTERDAY = new Date(NOW - 86400000);
const TWO_DAYS_AGO = new Date(NOW - 172800000);
const FIVE_DAYS_AGO = new Date(NOW - 432000000);
const ONE_WEEK_AGO = new Date(NOW - 604800000);
const THREE_DAYS_AGO = new Date(NOW - 259200000);

const TODAY_ISO = TODAY.toISOString();
const YESTERDAY_ISO = YESTERDAY.toISOString();
const TWO_DAYS_AGO_ISO = TWO_DAYS_AGO.toISOString();
const THREE_DAYS_AGO_ISO = THREE_DAYS_AGO.toISOString();
const FIVE_DAYS_AGO_ISO = FIVE_DAYS_AGO.toISOString();
const ONE_WEEK_AGO_ISO = ONE_WEEK_AGO.toISOString();

const GARDENS_MOCK = [
  {
    id: "g1",
    name: "Berçário / Vega",
    phase: "veg",
    environment: "indoor",
    day: 14,
    plantsCount: 6,
    startDate: new Date(NOW - 14 * 86400000),
    lastWateredDate: new Date(TODAY_ISO),
    stats: { temp: "26°C", hum: "65%", tempTarget: "28°C", humTarget: "70%" },
    imageColor: "#4ADE80",
    lightType: "T5",
    watts: "100",
    photoperiod: "18/6",
    substrate: "Turfa",
    plants: [
      { id: "101", name: "Lemon Skunk", strain: "Sativa", status: "healthy", ageDays: 14, origin: "seed", seedBank: "DNA Genetics", phenotype: "sativa", potSize: "4", notes: "Crescimento vigoroso, cheiro cítrico" },
      { id: "102", name: "Amnesia Haze", strain: "Sativa", status: "thirsty", ageDays: 12, origin: "seed", seedBank: "Royal Queen Seeds", phenotype: "sativa", potSize: "4", notes: "Precisa de mais água" },
      { id: "103", name: "Blue Dream", strain: "Hybrid", status: "healthy", ageDays: 10, origin: "seed", seedBank: "Humboldt Seeds", phenotype: "hybrid", potSize: "1", notes: "" },
      { id: "104", name: "Clone #1", strain: "Unknown", status: "healthy", ageDays: 5, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "0.5", notes: "Clone de GG4 Mãe" },
      { id: "105", name: "Clone #2", strain: "Unknown", status: "healthy", ageDays: 5, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "0.5", notes: "Clone de GG4 Mãe" },
      { id: "106", name: "Clone #3", strain: "Unknown", status: "thirsty", ageDays: 5, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "0.5", notes: "Raízes fracas, monitorar" },
    ],
  },
  {
    id: "g2",
    name: "Varanda Veg",
    phase: "veg",
    environment: "outdoor",
    day: 21,
    plantsCount: 3,
    startDate: new Date(NOW - 21 * 86400000),
    lastWateredDate: new Date(YESTERDAY_ISO),
    stats: { temp: "28°C", hum: "55%", tempTarget: "--", humTarget: "--" },
    imageColor: "#4ADE80",
    lightType: "Sol",
    watts: "∞",
    photoperiod: "Natural",
    substrate: "Solo Vivo",
    plants: [
      { id: "201", name: "Mango Kush", strain: "Indica", status: "healthy", ageDays: 21, origin: "seed", seedBank: "G13 Labs", phenotype: "indica", potSize: "7", notes: "Respondendo bem ao sol direto" },
      { id: "202", name: "Critical Mass", strain: "Hybrid", status: "healthy", ageDays: 18, origin: "seed", seedBank: "CBD Crew", phenotype: "hybrid", potSize: "7", notes: "" },
      { id: "203", name: "Durban Poison", strain: "Sativa", status: "thirsty", ageDays: 15, origin: "seed", seedBank: "Dutch Passion", phenotype: "sativa", potSize: "5", notes: "Seca rápido, regar 2x/dia" },
    ],
  },
  {
    id: "g3",
    name: "DWC Indoor",
    phase: "veg",
    environment: "hydroponic_indoor",
    day: 45,
    plantsCount: 2,
    startDate: new Date(NOW - 45 * 86400000),
    lastWateredDate: new Date(TODAY_ISO),
    stats: { temp: "20°C", hum: "60%", tempTarget: "20°C", humTarget: "60%" },
    imageColor: "#38BDF8",
    lightType: "LED",
    watts: "120",
    photoperiod: "20/4",
    substrate: "DWC",
    plants: [
      { id: "301", name: "DWC Test #1", strain: "Auto", status: "healthy", ageDays: 45, origin: "seed", seedBank: "Mephisto Genetics", phenotype: "hybrid", potSize: "DWC", notes: "Net pot 5cm, raízes longas" },
      { id: "302", name: "DWC Test #2", strain: "Auto", status: "healthy", ageDays: 40, origin: "seed", seedBank: "Mephisto Genetics", phenotype: "indica", potSize: "DWC", notes: "" },
    ],
  },
  {
    id: "g4",
    name: "Tenda Principal (80x80)",
    phase: "flower",
    environment: "indoor",
    day: 28,
    plantsCount: 4,
    startDate: new Date(NOW - 28 * 86400000),
    lastWateredDate: new Date(FIVE_DAYS_AGO_ISO),
    stats: { temp: "24°C", hum: "55%", tempTarget: "24°C", humTarget: "50%" },
    imageColor: "#A78BFA",
    lightType: "LED",
    watts: "240",
    photoperiod: "12/12",
    substrate: "Coco/Perlita",
    plants: [
      { id: "401", name: "Purple Haze #1", strain: "Sativa Dom", status: "healthy", ageDays: 65, origin: "seed", seedBank: "Positronics", phenotype: "sativa", potSize: "11", notes: "Esticou bastante no stretch" },
      { id: "402", name: "Gorilla Glue #4", strain: "Hybrid", status: "thirsty", ageDays: 42, origin: "clone", seedBank: "GG Strains", phenotype: "hybrid", potSize: "11", notes: "Muita resina, cuidado ao manusear" },
      { id: "403", name: "Gelato #33", strain: "Hybrid", status: "healthy", ageDays: 40, origin: "clone", seedBank: "Seed Junky", phenotype: "hybrid", potSize: "11", notes: "Cores roxas aparecendo" },
      { id: "404", name: "Wedding Cake", strain: "Indica", status: "healthy", ageDays: 38, origin: "seed", seedBank: "Barney's Farm", phenotype: "indica", potSize: "11", notes: "" },
    ],
  },
  {
    id: "g5",
    name: "Outdoor Guerrilha",
    phase: "flower",
    environment: "outdoor",
    day: 55,
    plantsCount: 2,
    startDate: new Date(NOW - 55 * 86400000),
    lastWateredDate: new Date(FIVE_DAYS_AGO_ISO),
    stats: { temp: "32°C", hum: "40%", tempTarget: "--", humTarget: "--" },
    imageColor: "#FBBF24",
    lightType: "Sol",
    watts: "∞",
    photoperiod: "Natural",
    substrate: "Solo Vivo",
    plants: [
      { id: "501", name: "Manga Rosa", strain: "Landrace", status: "healthy", ageDays: 120, origin: "seed", seedBank: "Landrace BR", phenotype: "sativa", potSize: "50", notes: "Planta enorme, aguenta o calor" },
      { id: "502", name: "24K Gold", strain: "Indica", status: "thirsty", ageDays: 90, origin: "seed", seedBank: "DNA Genetics", phenotype: "indica", potSize: "30", notes: "Buds densos, cheiro forte" },
    ],
  },
  {
    id: "g6",
    name: "NFT Flora",
    phase: "flower",
    environment: "hydroponic_indoor",
    day: 18,
    plantsCount: 3,
    startDate: new Date(NOW - 18 * 86400000),
    lastWateredDate: new Date(TODAY_ISO),
    stats: { temp: "22°C", hum: "50%", tempTarget: "22°C", humTarget: "50%" },
    imageColor: "#A78BFA",
    lightType: "LED",
    watts: "320",
    photoperiod: "12/12",
    substrate: "NFT",
    plants: [
      { id: "601", name: "White Widow", strain: "Hybrid", status: "healthy", ageDays: 55, origin: "seed", seedBank: "Green House Seeds", phenotype: "hybrid", potSize: "NFT", notes: "Adaptou bem ao NFT" },
      { id: "602", name: "AK-47", strain: "Hybrid", status: "healthy", ageDays: 52, origin: "seed", seedBank: "Serious Seeds", phenotype: "sativa", potSize: "NFT", notes: "" },
      { id: "603", name: "Northern Lights", strain: "Indica", status: "thirsty", ageDays: 50, origin: "clone", seedBank: "Sensi Seeds", phenotype: "indica", potSize: "NFT", notes: "Flow rate baixo, verificar bomba" },
    ],
  },
  {
    id: "g7",
    name: "Propagação (Clones)",
    phase: "nursery",
    environment: "indoor",
    day: 7,
    plantsCount: 8,
    startDate: new Date(NOW - 7 * 86400000),
    lastWateredDate: new Date(TODAY_ISO),
    stats: { temp: "25°C", hum: "80%", tempTarget: "25°C", humTarget: "85%" },
    imageColor: "#34D399",
    lightType: "CFL",
    watts: "45",
    photoperiod: "18/6",
    substrate: "Lã de Rocha",
    plants: [
      { id: "701", name: "GG4 Clone A", strain: "Hybrid", status: "healthy", ageDays: 7, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "Lã", notes: "Raízes visíveis" },
      { id: "702", name: "GG4 Clone B", strain: "Hybrid", status: "healthy", ageDays: 7, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "Lã", notes: "" },
      { id: "703", name: "GG4 Clone C", strain: "Hybrid", status: "thirsty", ageDays: 7, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "Lã", notes: "Sem raízes ainda" },
      { id: "704", name: "Gelato Clone A", strain: "Hybrid", status: "healthy", ageDays: 5, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "Lã", notes: "" },
      { id: "705", name: "Gelato Clone B", strain: "Hybrid", status: "healthy", ageDays: 5, origin: "clone", seedBank: "", phenotype: "hybrid", potSize: "Lã", notes: "" },
      { id: "706", name: "Semente Auto #1", strain: "Auto", status: "healthy", ageDays: 3, origin: "seed", seedBank: "FastBuds", phenotype: "hybrid", potSize: "Jiffy", notes: "Germinação ok" },
      { id: "707", name: "Semente Auto #2", strain: "Auto", status: "healthy", ageDays: 3, origin: "seed", seedBank: "FastBuds", phenotype: "hybrid", potSize: "Jiffy", notes: "" },
      { id: "708", name: "Semente Auto #3", strain: "Auto", status: "healthy", ageDays: 3, origin: "seed", seedBank: "FastBuds", phenotype: "indica", potSize: "Jiffy", notes: "" },
    ],
  },
  {
    id: "g8",
    name: "Mudas Outdoor",
    phase: "nursery",
    environment: "outdoor",
    day: 10,
    plantsCount: 4,
    startDate: new Date(NOW - 10 * 86400000),
    lastWateredDate: new Date(FIVE_DAYS_AGO_ISO),
    stats: { temp: "27°C", hum: "70%", tempTarget: "--", humTarget: "--" },
    imageColor: "#34D399",
    lightType: "Sol",
    watts: "∞",
    photoperiod: "Natural",
    substrate: "Solo",
    plants: [
      { id: "801", name: "Seedling #1", strain: "Unknown", status: "healthy", ageDays: 10, origin: "seed", seedBank: "", phenotype: "unknown", potSize: "0.5", notes: "" },
      { id: "802", name: "Seedling #2", strain: "Unknown", status: "healthy", ageDays: 10, origin: "seed", seedBank: "", phenotype: "unknown", potSize: "0.5", notes: "" },
      { id: "803", name: "Seedling #3", strain: "Unknown", status: "healthy", ageDays: 8, origin: "seed", seedBank: "", phenotype: "unknown", potSize: "0.3", notes: "" },
      { id: "804", name: "Seedling #4", strain: "Unknown", status: "thirsty", ageDays: 8, origin: "seed", seedBank: "", phenotype: "unknown", potSize: "0.3", notes: "Esticando, falta de luz" },
    ],
  },
  {
    id: "g9",
    name: "Secagem Lote #1",
    phase: "drying",
    environment: "indoor",
    day: 5,
    plantsCount: 3,
    startDate: new Date(NOW - 5 * 86400000),
    lastWateredDate: null,
    stats: { temp: "20°C", hum: "55%", tempTarget: "20°C", humTarget: "55%" },
    imageColor: "#F59E0B",
    lightType: "Escuro",
    watts: "0",
    photoperiod: "0/24",
    substrate: "N/A",
    plants: [
      { id: "901", name: "Purple Haze (Colheita)", strain: "Sativa", status: "healthy", ageDays: 95, origin: "seed", seedBank: "Positronics", phenotype: "sativa", potSize: "N/A", notes: "Pendurada inteira" },
      { id: "902", name: "OG Kush (Colheita)", strain: "Indica", status: "healthy", ageDays: 88, origin: "seed", seedBank: "Reserva Privada", phenotype: "indica", potSize: "N/A", notes: "Buds muito densos" },
      { id: "903", name: "Skunk #1 (Colheita)", strain: "Hybrid", status: "healthy", ageDays: 80, origin: "clone", seedBank: "Sensi Seeds", phenotype: "hybrid", potSize: "N/A", notes: "" },
    ],
  },
  {
    id: "g10",
    name: "Mães / Matrizes",
    phase: "mother",
    environment: "indoor",
    day: 120,
    plantsCount: 2,
    startDate: new Date(NOW - 120 * 86400000),
    lastWateredDate: new Date(TWO_DAYS_AGO_ISO),
    stats: { temp: "24°C", hum: "60%", tempTarget: "24°C", humTarget: "60%" },
    imageColor: "#06B6D4",
    lightType: "LED",
    watts: "150",
    photoperiod: "18/6",
    substrate: "Solo Orgânico",
    plants: [
      { id: "1001", name: "GG4 Mãe", strain: "Hybrid", status: "healthy", ageDays: 180, origin: "clone", seedBank: "GG Strains", phenotype: "hybrid", potSize: "20", notes: "Matriz principal, 30+ clones retirados" },
      { id: "1002", name: "Gelato Mãe", strain: "Hybrid", status: "healthy", ageDays: 150, origin: "seed", seedBank: "Seed Junky", phenotype: "hybrid", potSize: "15", notes: "Fenótipo roxo, produz bons clones" },
    ],
  },
  {
    id: "g11",
    name: "Hidro Outdoor (Estufa)",
    phase: "veg",
    environment: "hydroponic_outdoor",
    day: 30,
    plantsCount: 2,
    startDate: new Date(NOW - 30 * 86400000),
    lastWateredDate: new Date(TODAY_ISO),
    stats: { temp: "30°C", hum: "50%", tempTarget: "--", humTarget: "--" },
    imageColor: "#38BDF8",
    lightType: "Sol",
    watts: "∞",
    photoperiod: "Natural",
    substrate: "Hidro Gotejo",
    plants: [
      { id: "1101", name: "Sour Diesel", strain: "Sativa", status: "healthy", ageDays: 30, origin: "seed", seedBank: "Reserva Privada", phenotype: "sativa", potSize: "Gotejo", notes: "Crescimento explosivo" },
      { id: "1102", name: "Jack Herer", strain: "Sativa", status: "healthy", ageDays: 28, origin: "seed", seedBank: "Sensi Seeds", phenotype: "sativa", potSize: "Gotejo", notes: "" },
    ],
  },
];

const RECENT_LOGS = [
  {
    id: "w14",
    gardenId: "g4",
    gardenName: "Tenda Principal (80x80)",
    type: "water",
    note: "Calibração completa de nutrição com medições avançadas",
    date: new Date(TODAY_ISO),
    ph: "6.1",
    ec: "1.5",
    runoff_ec: "2.2",
    solution_temp: "20",
    vpd: "1.05",
    ppfd: "780",
    co2_ppm: "920",
    photoperiod: "12/12",
    water_liters: "4.5",
    nutrients_ml: "14",
    substrate_composition: "50% turfa, 30% perlita, 20% humus",
    fertilizer_type: "NPK Bloom + micros",
    fertilization_date: "2026-03-12",
    plant_height_cm: "68",
    harvest_forecast_date: "2026-04-06",
    plant_cost: "148.90",
    stress_observation: "Sem sinais de estresse térmico, folhas com boa turgidez",
  },
  {
    id: "p13",
    gardenId: "g4",
    gardenName: "Tenda Principal (80x80)",
    type: "prune",
    note: "Sessão de treino para abrir copa",
    date: new Date(YESTERDAY_ISO),
    training_type: "lst",
    technique_applied: "tech_lst",
    intensity: "intensity_moderate",
    plant_height_cm: "66",
    stress_observation: "Leve inclinação no ápice, recuperação em 24h",
  },
  {
    id: "i13",
    gardenId: "g5",
    gardenName: "Outdoor Guerrilha",
    type: "pest",
    note: "Inspeção preventiva e aplicação leve",
    date: new Date(TWO_DAYS_AGO_ISO),
    product: "Neem",
    dosage: "4ml/L",
    application_mode: "mode_foliar",
    safety_period: "0",
    pest_inspection: "inspection_attention",
    stress_observation: "Pontuais marcas em folhas inferiores; monitorar trips",
  },
  {
    id: "h2",
    gardenId: "g9",
    gardenName: "Secagem Lote #1",
    type: "harvest",
    note: "Registro pós-colheita do lote",
    date: new Date(ONE_WEEK_AGO_ISO),
    wet_weight: "1240",
    plant_cost: "392.00",
    harvest_forecast_date: "2026-03-05",
  },
  { id: "w3", gardenId: "g1", gardenName: "Berçário / Vega", type: "water", note: "Água pura", date: new Date(TWO_DAYS_AGO_ISO), ph: "7.0", water_liters: "2" },
  { id: "w7", gardenId: "g1", gardenName: "Berçário / Vega", type: "water", note: "CalMag apenas", date: new Date(TODAY_ISO), ph: "6.1", ec: "0.8", nutrients_ml: "5" },
  { id: "p1", gardenId: "g1", gardenName: "Berçário / Vega", type: "prune", note: "Poda Top (Apical)", date: new Date(TODAY_ISO), training_type: "apical", intensity: "intensity_moderate" },
  { id: "p2", gardenId: "g1", gardenName: "Berçário / Vega", type: "prune", note: "FIM", date: new Date(YESTERDAY_ISO), training_type: "fim", intensity: "intensity_moderate" },
  { id: "p7", gardenId: "g1", gardenName: "Berçário / Vega", type: "defoliate", note: "Remoção de folhas velhas", date: new Date(TODAY_ISO), training_type: "defoliation", intensity: "intensity_light" },
  { id: "p10", gardenId: "g1", gardenName: "Berçário / Vega", type: "prune", note: "LST contínuo", date: new Date(THREE_DAYS_AGO_ISO), training_type: "lst", intensity: "intensity_light" },
  { id: "i2", gardenId: "g1", gardenName: "Berçário / Vega", type: "fungi", note: "Leite Cru (Oídio)", date: new Date(YESTERDAY_ISO), product: "Leite", dosage: "10%", application_mode: "mode_foliar", safety_period: "0" },
  { id: "i7", gardenId: "g1", gardenName: "Berçário / Vega", type: "pest", note: "Armadilhas Amarelas", date: new Date(TODAY_ISO), product: "Sticky Trap", dosage: "N/A", application_mode: "mode_foliar", safety_period: "0" },
  { id: "i10", gardenId: "g1", gardenName: "Berçário / Vega", type: "pest", note: "Predadores Naturais", date: new Date(THREE_DAYS_AGO_ISO), product: "Joaninhas", dosage: "50 un", application_mode: "mode_foliar", safety_period: "0" },
  { id: "t1", gardenId: "g1", gardenName: "Berçário / Vega", type: "transplant", note: "Copo -> 1L", date: new Date(TODAY_ISO) },
  { id: "t2", gardenId: "g1", gardenName: "Berçário / Vega", type: "transplant", note: "1L -> 4L", date: new Date(YESTERDAY_ISO) },
  { id: "t6", gardenId: "g1", gardenName: "Berçário / Vega", type: "transplant", note: "Clones enraizados", date: new Date(ONE_WEEK_AGO_ISO) },
  { id: "t9", gardenId: "g1", gardenName: "Berçário / Vega", type: "transplant", note: "Replantio (Acidente)", date: new Date(TWO_DAYS_AGO_ISO) },
  { id: "f3", gardenId: "g1", gardenName: "Berçário / Vega", type: "flush", note: "Correção de EC", date: new Date(TWO_DAYS_AGO_ISO), water_liters: "10" },
  { id: "f7", gardenId: "g1", gardenName: "Berçário / Vega", type: "flush", note: "Lavagem de substrato novo", date: new Date(TODAY_ISO), water_liters: "15" },
  { id: "n2", gardenId: "g1", gardenName: "Berçário / Vega", type: "note", note: "Clones enraizando", date: new Date(YESTERDAY_ISO) },
  { id: "n6", gardenId: "g1", gardenName: "Berçário / Vega", type: "note", note: "Aumentar luz amanhã", date: new Date(ONE_WEEK_AGO_ISO) },
  { id: "n10", gardenId: "g1", gardenName: "Berçário / Vega", type: "note", note: "Comprar mais substrato", date: new Date(THREE_DAYS_AGO_ISO) },
  { id: "w11", gardenId: "g2", gardenName: "Varanda Veg", type: "water", note: "Rega matinal leve", date: new Date(TODAY_ISO), ph: "6.3", water_liters: "3" },
  { id: "w12", gardenId: "g2", gardenName: "Varanda Veg", type: "water", note: "Fertirrigação A+B", date: new Date(YESTERDAY_ISO), ph: "6.0", ec: "1.4", water_liters: "4", nutrients_ml: "10" },
  { id: "w13", gardenId: "g2", gardenName: "Varanda Veg", type: "water", note: "Água pura (runoff test)", date: new Date(THREE_DAYS_AGO_ISO), ph: "6.5", water_liters: "2" },
  { id: "p11", gardenId: "g2", gardenName: "Varanda Veg", type: "prune", note: "LST nas laterais", date: new Date(TWO_DAYS_AGO_ISO), training_type: "lst", intensity: "intensity_light" },
  { id: "p12", gardenId: "g2", gardenName: "Varanda Veg", type: "defoliate", note: "Desfolha folhas baixas", date: new Date(FIVE_DAYS_AGO_ISO), training_type: "defoliation", intensity: "intensity_light" },
  { id: "t11", gardenId: "g2", gardenName: "Varanda Veg", type: "transplant", note: "1L -> 7L cerâmica", date: new Date(YESTERDAY_ISO) },
  { id: "n11", gardenId: "g2", gardenName: "Varanda Veg", type: "note", note: "Mango Kush respondendo bem ao sol", date: new Date(TODAY_ISO) },
  { id: "n12", gardenId: "g2", gardenName: "Varanda Veg", type: "photo", note: "Foto do crescimento semanal", date: new Date(FIVE_DAYS_AGO_ISO) },
  { id: "w4", gardenId: "g3", gardenName: "DWC Indoor", type: "water", note: "Ajuste de pH (Baixo)", date: new Date(THREE_DAYS_AGO_ISO), ph: "5.8", ec: "1.0", solution_temp: "19" },
  { id: "w8", gardenId: "g3", gardenName: "DWC Indoor", type: "water", note: "Troca de reservatório", date: new Date(YESTERDAY_ISO), ph: "5.8", ec: "1.5", solution_temp: "21", water_liters: "40" },
  { id: "p6", gardenId: "g3", gardenName: "DWC Indoor", type: "prune", note: "Super Cropping (Acidental)", date: new Date(ONE_WEEK_AGO_ISO), training_type: "hst", intensity: "intensity_severe" },
  { id: "i6", gardenId: "g3", gardenName: "DWC Indoor", type: "pest", note: "H2O2 (Raízes)", date: new Date(ONE_WEEK_AGO_ISO), product: "Peróxido", dosage: "3ml/L", application_mode: "mode_soil", safety_period: "0" },
  { id: "t5", gardenId: "g3", gardenName: "DWC Indoor", type: "transplant", note: "Lã de rocha -> Argila", date: new Date(FIVE_DAYS_AGO_ISO) },
  { id: "t10", gardenId: "g3", gardenName: "DWC Indoor", type: "transplant", note: "Limpeza de sistema", date: new Date(THREE_DAYS_AGO_ISO) },
  { id: "f1", gardenId: "g3", gardenName: "DWC Indoor", type: "flush", note: "Flush semanal", date: new Date(TODAY_ISO), water_liters: "20" },
  { id: "f6", gardenId: "g3", gardenName: "DWC Indoor", type: "flush", note: "Troca total", date: new Date(ONE_WEEK_AGO_ISO), water_liters: "40" },
  { id: "f10", gardenId: "g3", gardenName: "DWC Indoor", type: "flush", note: "Manutenção", date: new Date(THREE_DAYS_AGO_ISO), water_liters: "25" },
  { id: "n4", gardenId: "g3", gardenName: "DWC Indoor", type: "note", note: "Raízes brancas e saudáveis", date: new Date(THREE_DAYS_AGO_ISO) },
  { id: "n8", gardenId: "g3", gardenName: "DWC Indoor", type: "note", note: "Calibrar caneta de pH", date: new Date(YESTERDAY_ISO) },
  { id: "w1", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "water", note: "Rega padrão", date: new Date(TODAY_ISO), ph: "6.2", ec: "1.2", water_liters: "5" },
  { id: "w2", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "water", note: "Nutrição pesada", date: new Date(YESTERDAY_ISO), ph: "5.5", ec: "2.8", water_liters: "5", nutrients_ml: "20" },
  { id: "w6", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "water", note: "Flush leve", date: new Date(ONE_WEEK_AGO_ISO), ph: "6.8", ec: "0.4", water_liters: "15" },
  { id: "w10", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "water", note: "Rega foliar", date: new Date(THREE_DAYS_AGO_ISO), ph: "6.0", ec: "0.6", water_liters: "1" },
  { id: "p3", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "prune", note: "LST Amarras", date: new Date(TWO_DAYS_AGO_ISO), training_type: "lst", intensity: "intensity_light" },
  { id: "p4", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "defoliate", note: "Desfolha pesada pré-flora", date: new Date(THREE_DAYS_AGO_ISO), training_type: "defoliation", intensity: "intensity_severe" },
  { id: "p8", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "prune", note: "Topping múltiplo", date: new Date(YESTERDAY_ISO), training_type: "apical", intensity: "intensity_severe" },
  { id: "i3", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "pest", note: "Beauveria Bassiana", date: new Date(TWO_DAYS_AGO_ISO), product: "Beauveria", dosage: "2g/L", application_mode: "mode_foliar", safety_period: "3" },
  { id: "i5", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "fungi", note: "Trichoderma", date: new Date(FIVE_DAYS_AGO_ISO), product: "Trichoderma", dosage: "1g/L", application_mode: "mode_soil", safety_period: "0" },
  { id: "i8", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "pest", note: "Abamectina (Emergência)", date: new Date(YESTERDAY_ISO), product: "Abamectina", dosage: "0.5ml/L", application_mode: "mode_foliar", safety_period: "14" },
  { id: "t3", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "transplant", note: "4L -> 11L (Final)", date: new Date(TWO_DAYS_AGO_ISO) },
  { id: "t7", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "transplant", note: "Top dressing", date: new Date(TODAY_ISO) },
  { id: "f2", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "flush", note: "Pré-colheita", date: new Date(YESTERDAY_ISO), water_liters: "50" },
  { id: "f5", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "flush", note: "Bloqueio de nutrientes", date: new Date(FIVE_DAYS_AGO_ISO), water_liters: "30" },
  { id: "f8", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "flush", note: "Finalização", date: new Date(YESTERDAY_ISO), water_liters: "60" },
  { id: "n1", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "photo", note: "Semana 5 Flora", date: new Date(TODAY_ISO) },
  { id: "n5", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "photo", note: "Tricomas leitosos", date: new Date(FIVE_DAYS_AGO_ISO) },
  { id: "n9", gardenId: "g4", gardenName: "Tenda Principal (80x80)", type: "photo", note: "Deficiência de Calcio?", date: new Date(TWO_DAYS_AGO_ISO) },
  { id: "w5", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "water", note: "Rega de emergência", date: new Date(FIVE_DAYS_AGO_ISO), water_liters: "10", ph: "6.3" },
  { id: "w9", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "water", note: "Chá de compostagem", date: new Date(TWO_DAYS_AGO_ISO), ph: "6.4", ec: "1.8", water_liters: "8" },
  { id: "p5", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "prune", note: "Limpeza de canelas", date: new Date(FIVE_DAYS_AGO_ISO), training_type: "lollipopping", intensity: "intensity_light" },
  { id: "p9", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "prune", note: "Poda de galhos baixos", date: new Date(TWO_DAYS_AGO_ISO), training_type: "lollipopping", intensity: "intensity_moderate" },
  { id: "i1", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "pest", note: "Óleo de Neem", date: new Date(TODAY_ISO), product: "Neem", dosage: "5ml/L", application_mode: "mode_foliar", safety_period: "0" },
  { id: "i4", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "pest", note: "Terra de Diatomáceas", date: new Date(THREE_DAYS_AGO_ISO), product: "Diatomáceas", dosage: "Pó", application_mode: "mode_soil", safety_period: "0" },
  { id: "i9", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "fungi", note: "Bicarbonato de Sódio", date: new Date(TWO_DAYS_AGO_ISO), product: "Bicarbonato", dosage: "1 colher/L", application_mode: "mode_foliar", safety_period: "0" },
  { id: "t4", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "transplant", note: "Solo direto", date: new Date(THREE_DAYS_AGO_ISO) },
  { id: "t8", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "transplant", note: "Preparo de covas", date: new Date(YESTERDAY_ISO) },
  { id: "f4", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "flush", note: "Chuva intensa (Natural)", date: new Date(THREE_DAYS_AGO_ISO), water_liters: "N/A" },
  { id: "f9", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "flush", note: "Rega pesada", date: new Date(TWO_DAYS_AGO_ISO), water_liters: "20" },
  { id: "n3", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "photo", note: "Ataque de lagartas controlado", date: new Date(TWO_DAYS_AGO_ISO) },
  { id: "n7", gardenId: "g5", gardenName: "Outdoor Guerrilha", type: "photo", note: "Pôr do sol", date: new Date(TODAY_ISO) },
  { id: "w20", gardenId: "g6", gardenName: "NFT Flora", type: "water", note: "Troca de solução nutritiva", date: new Date(TODAY_ISO), ph: "5.9", ec: "1.8", solution_temp: "20", water_liters: "30" },
  { id: "w21", gardenId: "g6", gardenName: "NFT Flora", type: "water", note: "Ajuste de pH", date: new Date(YESTERDAY_ISO), ph: "6.1", ec: "1.6", solution_temp: "21" },
  { id: "w22", gardenId: "g6", gardenName: "NFT Flora", type: "water", note: "Boost PK semana 4", date: new Date(THREE_DAYS_AGO_ISO), ph: "5.8", ec: "2.0", nutrients_ml: "15" },
  { id: "p20", gardenId: "g6", gardenName: "NFT Flora", type: "defoliate", note: "Desfolha leve inferior", date: new Date(TWO_DAYS_AGO_ISO), training_type: "defoliation", intensity: "intensity_light" },
  { id: "i20", gardenId: "g6", gardenName: "NFT Flora", type: "pest", note: "Neem preventivo", date: new Date(FIVE_DAYS_AGO_ISO), product: "Neem", dosage: "3ml/L", application_mode: "mode_foliar", safety_period: "0" },
  { id: "f20", gardenId: "g6", gardenName: "NFT Flora", type: "flush", note: "Flush de transição", date: new Date(ONE_WEEK_AGO_ISO), water_liters: "25" },
  { id: "n20", gardenId: "g6", gardenName: "NFT Flora", type: "photo", note: "Início das flores", date: new Date(TODAY_ISO) },
  { id: "n21", gardenId: "g6", gardenName: "NFT Flora", type: "note", note: "EC subindo rápido, monitorar", date: new Date(YESTERDAY_ISO) },
  { id: "w30", gardenId: "g7", gardenName: "Propagação (Clones)", type: "water", note: "Spray no dome", date: new Date(TODAY_ISO), ph: "6.0", water_liters: "0.5" },
  { id: "w31", gardenId: "g7", gardenName: "Propagação (Clones)", type: "water", note: "Umidificação da lã", date: new Date(YESTERDAY_ISO), ph: "5.8", water_liters: "0.3" },
  { id: "w32", gardenId: "g7", gardenName: "Propagação (Clones)", type: "water", note: "Enraizante diluído", date: new Date(THREE_DAYS_AGO_ISO), ph: "6.0", ec: "0.3", nutrients_ml: "2" },
  { id: "t20", gardenId: "g7", gardenName: "Propagação (Clones)", type: "transplant", note: "Corte de clones GG4", date: new Date(TODAY_ISO) },
  { id: "t21", gardenId: "g7", gardenName: "Propagação (Clones)", type: "transplant", note: "Semente germinada -> lã de rocha", date: new Date(TWO_DAYS_AGO_ISO) },
  { id: "n30", gardenId: "g7", gardenName: "Propagação (Clones)", type: "note", note: "Clone C sem raízes ainda", date: new Date(TODAY_ISO) },
  { id: "n31", gardenId: "g7", gardenName: "Propagação (Clones)", type: "note", note: "Abrir dome 2x ao dia para ventilação", date: new Date(YESTERDAY_ISO) },
  { id: "w40", gardenId: "g8", gardenName: "Mudas Outdoor", type: "water", note: "Rega leve ao amanhecer", date: new Date(TODAY_ISO), ph: "6.5", water_liters: "1" },
  { id: "w41", gardenId: "g8", gardenName: "Mudas Outdoor", type: "water", note: "Borrifação foliar", date: new Date(YESTERDAY_ISO), water_liters: "0.2" },
  { id: "t30", gardenId: "g8", gardenName: "Mudas Outdoor", type: "transplant", note: "Jiffy -> vaso 0.5L", date: new Date(TWO_DAYS_AGO_ISO) },
  { id: "i30", gardenId: "g8", gardenName: "Mudas Outdoor", type: "pest", note: "Canela em pó (antifúngico)", date: new Date(THREE_DAYS_AGO_ISO), product: "Canela", dosage: "Pó", application_mode: "mode_soil", safety_period: "0" },
  { id: "n40", gardenId: "g8", gardenName: "Mudas Outdoor", type: "note", note: "Seedling #4 esticando demais, mover p/ sol direto", date: new Date(TODAY_ISO) },
  { id: "n50", gardenId: "g9", gardenName: "Secagem Lote #1", type: "note", note: "Temp e umid estáveis, tudo ok", date: new Date(TODAY_ISO) },
  { id: "n51", gardenId: "g9", gardenName: "Secagem Lote #1", type: "note", note: "Galhos começando a estalar, quase pronto", date: new Date(YESTERDAY_ISO) },
  { id: "n52", gardenId: "g9", gardenName: "Secagem Lote #1", type: "note", note: "Pendurado com varal, dia 1", date: new Date(FIVE_DAYS_AGO_ISO) },
  { id: "n53", gardenId: "g9", gardenName: "Secagem Lote #1", type: "photo", note: "Foto do setup de secagem", date: new Date(FIVE_DAYS_AGO_ISO) },
  { id: "w50", gardenId: "g10", gardenName: "Mães / Matrizes", type: "water", note: "Fertirrigação leve", date: new Date(TODAY_ISO), ph: "6.2", ec: "1.0", water_liters: "3", nutrients_ml: "5" },
  { id: "w51", gardenId: "g10", gardenName: "Mães / Matrizes", type: "water", note: "Água pura", date: new Date(THREE_DAYS_AGO_ISO), ph: "6.5", water_liters: "2" },
  { id: "p30", gardenId: "g10", gardenName: "Mães / Matrizes", type: "prune", note: "Poda de manutenção semanal", date: new Date(TODAY_ISO), training_type: "apical", intensity: "intensity_light" },
  { id: "p31", gardenId: "g10", gardenName: "Mães / Matrizes", type: "prune", note: "Retirada de cortes p/ clonagem", date: new Date(YESTERDAY_ISO), training_type: "apical", intensity: "intensity_moderate" },
  { id: "t40", gardenId: "g10", gardenName: "Mães / Matrizes", type: "transplant", note: "Top dressing orgânico", date: new Date(ONE_WEEK_AGO_ISO) },
  { id: "n60", gardenId: "g10", gardenName: "Mães / Matrizes", type: "note", note: "GG4 Mãe muito vigorosa, podar mais seguido", date: new Date(TODAY_ISO) },
  { id: "w60", gardenId: "g11", gardenName: "Hidro Outdoor (Estufa)", type: "water", note: "Ajuste de pH solução", date: new Date(TODAY_ISO), ph: "5.9", ec: "1.5", solution_temp: "24", water_liters: "15" },
  { id: "w61", gardenId: "g11", gardenName: "Hidro Outdoor (Estufa)", type: "water", note: "Reposição de reservatório", date: new Date(TWO_DAYS_AGO_ISO), ph: "6.0", ec: "1.3", water_liters: "20" },
  { id: "p40", gardenId: "g11", gardenName: "Hidro Outdoor (Estufa)", type: "prune", note: "Topping Jack Herer", date: new Date(YESTERDAY_ISO), training_type: "apical", intensity: "intensity_moderate" },
  { id: "i40", gardenId: "g11", gardenName: "Hidro Outdoor (Estufa)", type: "pest", note: "Neem preventivo estufa", date: new Date(THREE_DAYS_AGO_ISO), product: "Neem", dosage: "4ml/L", application_mode: "mode_foliar", safety_period: "0" },
  { id: "n70", gardenId: "g11", gardenName: "Hidro Outdoor (Estufa)", type: "note", note: "Sol forte demais, colocar sombrite 50%", date: new Date(TODAY_ISO) },
  { id: "n71", gardenId: "g11", gardenName: "Hidro Outdoor (Estufa)", type: "photo", note: "Raízes no gotejador", date: new Date(FIVE_DAYS_AGO_ISO) },
];

const INVENTORY_MOCK = [
  {
    id: "inv1",
    name: "Base Flora A+B",
    category: "Nutrientes Líquidos",
    quantity: 1.0,
    unit: "L",
    minStock: 0.5,
    brand: "BioGrow Labs",
    supplier: "Grow Center SP",
    batchCode: "BG-FA-2402",
    storageLocation: "Prateleira A1",
    costPerUnit: 189.9,
    expiryDate: new Date("2026-12-01T00:00:00.000Z"),
    lastRestockDate: new Date("2026-03-01T00:00:00.000Z"),
    notes: "Linha principal de floração",
    lastUpdated: new Date(TODAY_ISO),
  },
  {
    id: "inv2",
    name: "CalMag",
    category: "Corretores",
    quantity: 250,
    unit: "mL",
    minStock: 100,
    brand: "Green Elements",
    supplier: "HydroShop BH",
    batchCode: "GE-CM-2401",
    storageLocation: "Prateleira B2",
    costPerUnit: 79.5,
    expiryDate: new Date("2026-09-15T00:00:00.000Z"),
    lastRestockDate: new Date("2026-02-20T00:00:00.000Z"),
    notes: "Usar 1-2ml/L conforme rótulo",
    lastUpdated: new Date(YESTERDAY_ISO),
  },
  {
    id: "inv3",
    name: "Substrato Orgânico",
    category: "Substratos",
    quantity: 20,
    unit: "L",
    minStock: 10,
    brand: "Solo Vivo",
    supplier: "AgroViva",
    batchCode: "SV-ORG-2399",
    storageLocation: "Depósito 02",
    costPerUnit: 54.0,
    expiryDate: null,
    lastRestockDate: new Date("2026-02-10T00:00:00.000Z"),
    notes: "Mistura viva para transplantes",
    lastUpdated: new Date(FIVE_DAYS_AGO_ISO),
  },
];

module.exports = { GARDENS_MOCK, RECENT_LOGS, INVENTORY_MOCK };
